### ISSUE TITLE
Community pages - blog, team profile, etc

### ISSUE THREAD

**Issue by tombh** [hotosm/openaerialmap.org#24]
As part of the Diffusion milestone we would like to focus on OAM/OIN's reach into the wider world. Part of that can be achieved by giving the teams and inner workings more exposure. So classic examples of that are a blog and team pages.

- [ ] Add a Static Site Generator, like Jekyll.
- [ ] Who should be on the team page?
- [ ] What are examples of blog post topics?
- [ ] What should the design of these pages be?

**Comment by tombh** [comment]
One example of a blog post is the recent 'Jakarta Jam' me and @smit1678 had. We could write up who we met, what we talked about and what we hope to achieve from it all.

Also I'd love to write about the technical things I'm working on at the moment. Merging git repos, writing integration tests that work locally and on Browser Stack, the vision of the dynamic tiler, etc.

**Comment by smit1678** [comment]
Suggestion here for blog: leverage Medium. I started a test of an OpenAerialMap publication: https://medium.com/openaerialmap. We can add a custom domain, like `blog.openaerialmap.org`, to make it feel more integrated. There are some other customizations that we can do to brand it as well. 

The thinking here is to potentially enable both a wider reach of blog posts, but also to enable community contributions of blog posts and updates. I think a jekyll site with blogging would be great, but this may be more in line with how we can grow community contributions.

**Comment by smit1678** [comment]
Stale and closing.
