### ISSUE TITLE
Integrate blog

### ISSUE THREAD

**Issue by smit1678** [hotosm/openaerialmap.org#25]
Blog is setup at https://blog.openaerialmap.org/. Next step is to integrate. 

@brendangatens For now just thinking of this type of integration: 

![openaerialmap 2017-08-08 18-06-21](https://user-images.githubusercontent.com/796838/29084570-571b81ce-7c64-11e7-97c6-6f4cf57d0426.png)

Do we want to go ahead and start to make the shift towards: 

![openaerialmap 2017-08-08 18-09-58](https://user-images.githubusercontent.com/796838/29084715-db44b448-7c64-11e7-92fb-183a0e824d38.png)

**Comment by brendangatens** [comment]
I think this is a step in the right direction. We could be even more specific and say something like "Explore imagery" or "Explore the map". Maybe the point is to not be too specific, however, as users' intentions will vary.

**Comment by smit1678** [comment]
This has been done. :+1:
