### ISSUE TITLE
Point DNS to github repo

### ISSUE THREAD

**Issue by smit1678** [hotosm/openaerialmap.org#3]
@cgiovando We have the ability to hook up openaerialmap.org to the repo here. Can you point the DNS to Github: https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/?

**Comment by cgiovando** [comment]
Does this look right?

![screen shot 2015-04-30 at 15 36 40](https://cloud.githubusercontent.com/assets/10201533/7420933/c2c8a6ea-ef4e-11e4-8433-5e795b6486bd.png)

**Comment by smit1678** [comment]
@cgiovando This looks good. Thanks.
